// ─── MULTI-FORMAT EXPORT ENGINE ─────────────────────────────────────────────
// YourBento Studio — Production-ready code generation

import type { GridCardData, GridConfig } from "../types";

export type ExportConfig = {
  themeColor: string;
  themeStyle: string;
  gridConfig: GridConfig;
};

// ─── CSS EXPORT ─────────────────────────────────────────────────────────────

export function exportCSS(config: ExportConfig): string {
  const c = config.gridConfig;
  return `/* Generated by YourBento Studio */
/* Theme: ${config.themeColor} | Style: ${config.themeStyle} */

.bento-grid {
  display: grid;
  grid-template-columns: repeat(${c.columns}, 1fr);
  grid-auto-rows: ${c.rowHeight}px;
  gap: ${c.gap}px;
  max-width: ${c.maxWidth}px;
  margin: 0 auto;
  padding: 2rem;
}

.bento-card {
  border-radius: 16px;
  padding: 2rem;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.bento-card:hover {
  transform: translateY(-4px);
}

.bento-card h3 {
  font-size: 1.4rem;
  font-weight: 800;
  margin-bottom: 0.5rem;
}

.bento-card p {
  font-weight: 600;
  opacity: 0.8;
}

.stat-number {
  font-size: 3rem;
  font-weight: 800;
  margin: auto 0;
  letter-spacing: -2px;
}

.start-btn {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px;
  border: 2px solid currentColor;
  border-radius: 8px;
  font-weight: 800;
  font-size: 1rem;
  cursor: pointer;
  background: transparent;
  transition: all 0.15s ease;
}

@media (max-width: 768px) {
  .bento-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 480px) {
  .bento-grid { grid-template-columns: 1fr; }
}
`;
}

// ─── REACT EXPORT ───────────────────────────────────────────────────────────

export function exportReact(cards: GridCardData[], config: ExportConfig): string {
  const cardsJSON = JSON.stringify(cards.map(simplify), null, 2);

  return `// Generated by YourBento Studio
// Theme: ${config.themeColor} | Style: ${config.themeStyle}

import React from "react";
import "./bento.css";

const GRID_DATA = ${cardsJSON};

export default function BentoGrid() {
  return (
    <div className="bento-grid">
      {GRID_DATA.map((card) => (
        <div
          key={card.id}
          className="bento-card"
          style={{
            gridColumn: \`span \${card.colSpan}\`,
            gridRow: \`span \${card.rowSpan}\`,
            borderRadius: \`\${card.borderRadius}px\`,
            backgroundColor: card.bgColor,
          }}
        >
          <h3>{card.title}</h3>
          <p>{card.subtitle}</p>
          {card.statValue && <div className="stat-number">{card.statValue}</div>}
          {card.buttonText && <button className="start-btn">{card.buttonText}</button>}
        </div>
      ))}
    </div>
  );
}
`;
}

// ─── HTML EXPORT ────────────────────────────────────────────────────────────

export function exportHTML(cards: GridCardData[], config: ExportConfig): string {
  const c = config.gridConfig;
  const cardDivs = cards.map((card) => {
    let inner = `      <h3>${card.title}</h3>\n      <p>${card.subtitle}</p>`;
    if (card.statValue) inner += `\n      <div class="stat-number">${card.statValue}</div>`;
    if (card.buttonText) inner += `\n      <button class="start-btn">${card.buttonText}</button>`;
    return `    <div class="bento-card" style="grid-column: span ${card.colSpan}; grid-row: span ${card.rowSpan}; border-radius: ${card.borderRadius}px;">\n${inner}\n    </div>`;
  }).join("\n\n");

  return `<!-- Generated by YourBento Studio -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>My Bento Grid</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; background: #f5f5f5; }
    .bento-grid {
      display: grid;
      grid-template-columns: repeat(${c.columns}, 1fr);
      grid-auto-rows: ${c.rowHeight}px;
      gap: ${c.gap}px;
      max-width: ${c.maxWidth}px;
      margin: 2rem auto;
      padding: 0 2rem;
    }
    .bento-card {
      padding: 2rem;
      display: flex;
      flex-direction: column;
      position: relative;
      overflow: hidden;
      background: #fff;
      border: 2px solid #222;
      transition: transform 0.2s ease;
    }
    .bento-card:hover { transform: translateY(-4px); }
    .bento-card h3 { font-size: 1.4rem; font-weight: 800; margin-bottom: 0.5rem; }
    .bento-card p { font-weight: 600; opacity: 0.7; }
    .stat-number { font-size: 3rem; font-weight: 800; margin: auto 0; }
    .start-btn {
      display: inline-flex; align-items: center; gap: 8px;
      padding: 12px 24px; border: 2px solid #222; border-radius: 8px;
      font-weight: 800; background: transparent; cursor: pointer;
    }
    @media (max-width: 768px) { .bento-grid { grid-template-columns: repeat(2, 1fr); } }
    @media (max-width: 480px) { .bento-grid { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <div class="bento-grid">
${cardDivs}
  </div>
</body>
</html>
`;
}

// ─── VUE EXPORT ─────────────────────────────────────────────────────────────

export function exportVue(cards: GridCardData[], _config: ExportConfig): string {
  const cardsJSON = JSON.stringify(cards.map(simplify), null, 2);

  return `<!-- Generated by YourBento Studio -->
<template>
  <div class="bento-grid">
    <div
      v-for="card in gridData"
      :key="card.id"
      class="bento-card"
      :style="{
        gridColumn: 'span ' + card.colSpan,
        gridRow: 'span ' + card.rowSpan,
        borderRadius: card.borderRadius + 'px',
      }"
    >
      <h3>{{ card.title }}</h3>
      <p>{{ card.subtitle }}</p>
      <div v-if="card.statValue" class="stat-number">{{ card.statValue }}</div>
      <button v-if="card.buttonText" class="start-btn">{{ card.buttonText }}</button>
    </div>
  </div>
</template>

<script setup lang="ts">
const gridData = ${cardsJSON};
</script>

<style scoped>
@import "./bento.css";
</style>
`;
}

// ─── JSON EXPORT ────────────────────────────────────────────────────────────

export function exportJSON(cards: GridCardData[], config: ExportConfig): string {
  return JSON.stringify({
    meta: {
      generator: "YourBento Studio",
      version: "1.0.0",
      themeColor: config.themeColor,
      themeStyle: config.themeStyle,
      gridConfig: config.gridConfig,
      exportedAt: new Date().toISOString(),
    },
    cards,
  }, null, 2);
}

// ─── Simplify cards for export (remove internal fields) ──────────────────────

function simplify(card: GridCardData) {
  return {
    id: card.id,
    type: card.type,
    title: card.title,
    subtitle: card.subtitle,
    colSpan: card.colSpan,
    rowSpan: card.rowSpan,
    borderRadius: card.borderRadius,
    bgColor: card.bgColor,
    ...(card.statValue ? { statValue: card.statValue } : {}),
    ...(card.buttonText ? { buttonText: card.buttonText } : {}),
  };
}
